spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=validate

server.servlet.context-path=/api

jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.chat.id=${TELEGRAM_CHAT_ID}

stripe.secret=${STRIPE_SECRET_KEY}

app.payment.success-url=${PAYMENT_SUCCESS_URL}
app.payment.cancel-url=${PAYMENT_CANCEL_URL}
